claude-4-0:
  max_output_tokens: 1553
  output_token_price: 1.5e-05
  output_tokens_mu: 737.482
  price_mu: 0.01106223
  score_mu: 0.5752562632679845
deepseek-r1:
  max_output_tokens: 17627
  output_token_price: 2.1899999999999998e-06
  output_tokens_mu: 10833.1335
  price_mu: 0.023724562364999997
  score_mu: 0.5374994397769133

gpt-5-high:
  max_output_tokens: 37320
  output_token_price: 1.0e-05
  output_tokens_mu: 7010.0305
  price_mu: 0.070100305
  score_mu: 0.9922689280268833

gpt-5-medium:
  max_output_tokens: 38058
  output_token_price: 1.0e-05
  output_tokens_mu: 6635.639
  price_mu: 0.06635639
  score_mu: 0.9912244493848982

o1-mini:
  max_output_tokens: 11739
  output_token_price: 4.4e-06
  output_tokens_mu: 3857.731
  price_mu: 0.016974016400000003
  score_mu: 0.592180303108145
o3-mini:
  max_output_tokens: 27132
  output_token_price: 4.4e-06
  output_tokens_mu: 8354.085
  price_mu: 0.036757974
  score_mu: 0.7787893123421102
