gamma: 5
reward_param: 1.0
providers:
- id: 0
  num_models: 3
  eta: 0.9
  models:
  - gpt-5-high
  - deepseek-r1
  - gpt-5-medium
- id: 1
  num_models: 3
  eta: 0.9
  models:
  - o3-mini
  - o1-mini
  - deepseek-r1
- id: 2
  num_models: 3
  eta: 0.9
  models:
  - claude-4-0
  - o1-mini
  - deepseek-r1
