providers:
- id: 0
  num_models: 3
  eta: 0.9
  models:
  - o1-mini
  - o3-mini
  - o4-mini
- id: 1
  num_models: 3
  eta: 0.9
  models:
  - deepseek-r1
  - claude-4-0
  - o1-mini
- id: 2
  num_models: 3
  eta: 0.9
  models:
  - gpt-4
  - o1
  - gpt-35-turbo
