num_tasks: 10000
epsilon: 0.3
gamma: 2
reward_param: 3
input_tokens_mu: 500
input_tokens_gamma: 70
L: 1500
providers:
  - id: 0
    num_models: 3
    eta: 1
    models: [provider-1-good, provider-1-medium, provider-1-weak]
  - id: 1
    num_models: 3
    eta: 1
    models: [provider-2-good, provider-2-medium, provider-2-weak]
  - id: 2
    num_models: 3
    eta: 1
    models: [provider-3-good, provider-3-medium, provider-3-weak]