num_tasks: 1000000
epsilon: 0.3
gamma: 2
reward_param: 5
input_token_mu: 500
input_token_sigma: 50

providers:
  - id: 0
    num_models: 3
    eta: 0.9
    models: [provider-1-good, provider-1-mid, provider-1-weak]
  - id: 1
    num_models: 3
    eta: 0.9
    models: [provider-2-good, provider-2-mid, provider-2-weak]
  - id: 2
    num_models: 3
    eta: 0.9
    models: [provider-3-good, provider-3-mid, provider-3-weak]