provider-1-good:
  score_mu: 0.9
  score_sigma: 0
  output_tokens_mu: 1000
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.0006
  output_token_price: 0.0006

provider-1-medium:
  score_mu: 0.85
  score_sigma: 0
  output_tokens_mu: 900
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.0005
  output_token_price: 0.0005

provider-1-weak:
  score_mu: 0.6
  score_sigma: 0
  output_tokens_mu: 800
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.0004
  output_token_price: 0.0004
  

provider-2-good:
  score_mu: 0.75
  score_sigma: 0
  output_tokens_mu: 950
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.00055
  output_token_price: 0.00055

provider-2-medium:
  score_mu: 0.7
  score_sigma: 0
  output_tokens_mu: 900
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.0005
  output_token_price: 0.0005
  

provider-2-weak:
  score_mu: 0.65
  score_sigma: 0
  output_tokens_mu: 850
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.00045
  output_token_price: 0.00045

provider-3-good:
  score_mu: 0.75
  score_sigma: 0
  output_tokens_mu: 900
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.0005
  output_token_price: 0.0005

provider-3-medium:
  score_mu: 0.7
  score_sigma: 0
  output_tokens_mu: 850
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.00045
  output_token_price: 0.00045

provider-3-weak:
  score_mu: 0.65
  score_sigma: 0
  output_tokens_mu: 700
  output_tokens_sigma: 0
  max_output_tokens: 1500
  input_token_price: 0.0004
  output_token_price: 0.0004




