num_tasks: 1000
epsilon: 0.2
reward_param: 1
task_ids_path: data/task_ids_shuffled.json
providers:
  - id: 0
    models: ["o1","o1-mini","gpt-4o-mini"]
    eta: 0.2
  - id: 1
    models: ["o3-mini","deepseek-r1","deepseek-v3"]
    eta: 0.6
  - id: 2
    models: ["gpt-4","gpt-4o","gpt-35-turbo"]
    eta: 0.4
