num_tasks: 1000
epsilon: 0.3
reward_param: 3
task_ids_path: data/task_ids_shuffled.json
gamma: 2
providers:
  - id: 0
    models: ["claude-4-0","gpt-4o","gpt-35-turbo"]
    eta: 0.5
  - id: 1
    models: ["claude-4-0","gpt-4o","gpt-35-turbo"]
    eta: 0.5
  - id: 2
    models: ["claude-4-0","gpt-4o","gpt-35-turbo"]
    eta: 0.5
